# Generated by Django 3.1.4 on 2024-07-15 06:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('Assignment_name', models.CharField(max_length=200)),
                ('Grade', models.CharField(max_length=200)),
                ('Out_Of_Grade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='store_email_stu_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.CharField(max_length=100)),
                ('Student_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='store_email_teach_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_ID', models.CharField(max_length=100)),
                ('Teacher_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student_courses_with_Teacher_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Submit_Assignment_pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.CharField(max_length=1000)),
                ('course', models.CharField(max_length=1000)),
                ('Student_ID', models.CharField(max_length=1000)),
                ('Assignment_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Assignment_upload_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assignment_name', models.CharField(max_length=500)),
                ('course', models.CharField(max_length=500)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=500)),
                ('Details', models.TextField(max_length=500)),
                ('attachment', models.CharField(max_length=1000)),
                ('resource', models.CharField(max_length=500)),
                ('posts', models.CharField(max_length=500)),
                ('Out_Of_Grade', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_login_informa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_ID', models.CharField(max_length=50)),
                ('Teacher_Name', models.CharField(max_length=255)),
                ('Teacher_pass', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student_login_informatn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.CharField(max_length=50)),
                ('Student_Name', models.CharField(max_length=255)),
                ('Student_pass', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student_courses_with_teacher_name')),
            ],
        ),
        migrations.AddField(
            model_name='student_courses_with_teacher_name',
            name='Teacher_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.teacher_login_informa'),
        ),
        migrations.CreateModel(
            name='Assignment_Comments',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('postID', models.CharField(max_length=255)),
                ('time_comment', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.assignment_comments')),
            ],
        ),
    ]
